### ISSUE TITLE
Expose headers and remote ip on feathers object

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-primus#46]
This is too common of a request to not be next on the list.  There are a lot of headers that match between the transports: https://gist.github.com/marshallswain/b775c7b6d7a9b2429b0eb6fe669a2bfd  

We don't currently expose these headers for sockets.

```js
// This is for socket.io, but I imagine it's similar.
app.configure(socketio(function (io) {
  io.on('connection', function (socket) {
    Object.assign(socket.feathers, {headers: socket.handshake.headers});
    socket.feathers.ip = socket.conn.remoteAddress;
  });
}));
```

**Comment by daffl** [comment]
Do you mean add it by default or have it documented? We have an [FAQ entry](https://docs.feathersjs.com/help/faq.html#how-do-i-access-the-request-object-in-hooks-or-services) explaining why tacking on transport specific  parameters is not ideal and will tie your services to the transport protocol so I'm not sure this should be done.

**Comment by marshallswain** [comment]
I think we should add it by default.  We could even pick out the ones that match in all providers.

**Comment by marshallswain** [comment]
If not, I can make a plugin that does this.

**Comment by marshallswain** [comment]
I actually knew that we've turned this down several times, but after looking at it in more detail, I think that there's enough that matches up between providers that we could add this by default to each provider.

**Comment by daffl** [comment]
But what for? The only time we really need this is for the authentication service. 

Adding this by default is another layer of conventions that has to be documented, tested and will make services harder to test (you have to fake out headers if you need them). It will also break with the idea of services being transport independent. There are many potential new transports like ZeroMQ that don't have HTTP headers at all. Additionally, the headers for websockets are not too useful for us. It is the header from the time when the websocket connection has been established and especially in our case (where authentication goes through the existing socket connection instead of using the Authorization header) does not really contain much useful information.

I'd rather show how to add a the three lines of middleware to add the information you want than causing any confusion about what parameters to expect when (I can already see having to explain all the time that if you make your service call internally all that info won't be available).

**Comment by marshallswain** [comment]
Ok.  I agree.  The user agent is possibly the only useful thing from the websocket headers.
